/*
 * solido_rigido.h
 *
 *  Created on: 8 Oct 2019
 *      Author: Francisco Dominguez
 */

#ifndef SOLID_RIGID_BODY_H_
#define SOLID_RIGID_BODY_H_
#include <opencv2/opencv.hpp>
#include "solido.h"

//for the moment are just boxes
class SolidRigidBody: public Solido {
	Mat R;      // Orientation matrix
	Mat w;      // Angular velocity (Vector3D column)
	Mat Ib;     // Inertia tensor of initial body pose
	Mat Ibinv;  // Inverse inertia tensor of initial body pose
	Mat Iinv;   // Inverse of Inertia Tensor
	Mat L;      // Angular momentum (Vector3D column)
	Mat T;      // Total Torque or Total Angular Force
	double staticFriction;
	double dynamicFriction;
	double restitution;
	vector<Vector3D> corners;
public:
	Texture tex;
	inline double getRestitution()    {return restitution;}
	inline double getStaticFriction() {return staticFriction;}
	inline double getDynamicFriction(){return dynamicFriction;}
	double getInvM(){
		if(esFija()) return 0;
		return 1.0/getM();
	}
	Mat getInvI(){
		if(esFija()) return Mat::zeros(3,3,CV_64F);
		Iinv=R*Ibinv*R.t();
		return Iinv;
	}
	void setRot(Vector3D r){
		Solido::setRot(r);
		R=eulerAnglesToRotationMatrix(r);
	}
	void setRot(Mat r){R=r;}
	void setPos(Vector3D p){Solido::setPos(p);}
	void setPos(Mat p){setPos(Vector3D(p.at<double>(0,0),
			                           p.at<double>(1,0),
									   p.at<double>(2,0)));
	}
	void setVel(Vector3D p){Solido::setVel(p);}
	void setVel(Mat v){setVel(Vector3D(v.at<double>(0,0),
			                           v.at<double>(1,0),
									   v.at<double>(2,0)));
	}
	Vector3D getRot(){return rotationMatrixToEulerAngles(R);}
	Mat &getRotMat(){return R;}
	Vector3D getW(){return Vector3D(w.at<double>(0,0),w.at<double>(1,0),w.at<double>(2,0));}
	Mat  getPosMat(){return getPos().asMat();}
	Mat  getVelMat(){return getVel().asMat();}
	SolidRigidBody(double w2,double h2,double d2){
		R=Mat::eye(3,3,CV_64F);   // Identity matrix
		//w=Mat:.zeros(3,1,CV_64F); // Not angular velocity yet
		L=Mat::zeros(3,1,CV_64F); // Not angular mometum yet
		//L.at<double>(0,0)=0.0;
		//L.at<double>(2,0)=0.0;
		//L.at<double>(2,0)=0.0;
		T=Mat::zeros(3,1,CV_64F); // Not torque yet
		// Rectangular block Inertial tensor
		Ib=Mat::zeros(3,3,CV_64F);
		double m=getM();
		Ib.at<double>(0,0)=m*(w2*w2+h2*h2)/12;;
		Ib.at<double>(1,1)=m*(d2*d2+h2*h2)/12;;
		Ib.at<double>(2,2)=m*(w2*w2+d2*d2)/12;;
		Ibinv=Ib.inv();
		updateWIinv();
		staticFriction=0;
		dynamicFriction=0;
		restitution=0.9;
		// shape
		double w=w2/2;
		double h=h2/2;
		double d=d2/2;
		//     5---1
		//    /   /|
		//   4---0 |
		//   |   | 2
		//   |   |/
		//   7---3
		//square of the right
		//right/up/front point
		Vector3D p;
		p=Vector3D( w, h, d);
		corners.push_back(p);
		//right/up/back point
		p=Vector3D( w, h,-d);
		corners.push_back(p);
		//right/bottom/back point
		p=Vector3D( w,-h,-d);
		corners.push_back(p);
		//right/bottom/front point
		p=Vector3D( w,-h, d);
		corners.push_back(p);
		//squre of the left
		p=Vector3D(-w, h, d);
		corners.push_back(p);
		p=Vector3D(-w, h,-d);
		corners.push_back(p);
		p=Vector3D(-w,-h,-d);
		corners.push_back(p);
		p=Vector3D(-w,-h, d);
		corners.push_back(p);
		setCol(Vector3D(0.9,0.9,0));
	}
	inline Vector3D getCorner(int i){
		Mat c=asMat(corners[i]);
		Mat p;
		p=R*c;
		return asVector3D(p)+getPos();
	}
	void updateWIinv(){
		w=getInvI()*L;
	}
	void update(double dt){
		// ground collision
		Vector3D pcm=getPos();
		// LINEAR UPDATE
		//Solido::update(dt);
		Vector3D vel=getVel()+getF()*getInvM()*dt;
		setVel(vel);
		Vector3D pos=getPos()+vel*dt;
		setPos(pos);

		// ANGULAR UPDATE
		// Update orientation
		// Get the orientation increment in axis angle form
		Mat dw;
		dw=w*dt;
		// Get the orientation increment in matrix form with Rodrigues formula
		Mat dR;
		Rodrigues(dw,dR);
		// update orientation matrix
		R=dR*R;
		// Update angular momentum
		L=L+T*dt;
		cout <<"F="<<getF()<<endl;
		cout <<"V="<<getVel()<<endl;
		cout <<"T="<< T.at<double>(0,0)<<","<< T.at<double>(1,0)<<","<< T.at<double>(2,0)<<endl;
		cout <<"L="<< L.at<double>(0,0)<<","<< L.at<double>(1,0)<<","<< L.at<double>(2,0)<<endl;
		cout <<"R="<< getRot() <<endl;
		// Update Inverse inertia tensor with new orientation
		// and Angular velocity with new inverse Inertia tensor
		updateWIinv();
	}
	virtual void limpiaTorque(){T=Mat::zeros(3,1,CV_64F);}
	void limpiaFuerza(){
		Solido::limpiaFuerza();
		limpiaTorque();
	}
	//Compute torque generated by a force f in a point pw of this solid
	virtual Vector3D torqueFromForce(Vector3D f, Vector3D pw){
		Vector3D pcm=getPos();
		Vector3D pb=pw-pcm;// position on body frame
		Vector3D torque=pb.X(f);
		return torque;
	}
	virtual void aplicaTorque (Vector3D tv){
		Mat tm=asMat(tv);
		T=T+tm;
	}
	void applyImpulse(Vector3D impulse,Vector3D contactVector){
		setVel(getVel()+impulse*getInvM());
		Vector3D cvi=contactVector.X(impulse);
		w+=getInvI()*cvi.asMat();
	}
	//     5---1
	//    /   /|
	//   4---0 |
	//   |   | 2
	//   |   |/
	//   7---3
	//square of the right
	//right/up/front point
	inline void render(){
		glPushMatrix();
		//glTranslatef(this->getPos().getX(),this->getPos().getY(),this->getPos().getZ());
		Rectangulo r0(
				getCorner(0),
				getCorner(1),
				getCorner(2),
				getCorner(3));
		//r0.getTex()=tex;
		r0.setCol(getCol());
		r0.render();
		Rectangulo r1(
				getCorner(4),
				getCorner(5),
				getCorner(6),
				getCorner(7));
		//r1.getTex()=tex;
		r1.render();
		Rectangulo r2(
				getCorner(0),
				getCorner(3),
				getCorner(7),
				getCorner(4));
		//r2.getTex()=tex;
		r2.render();
		Rectangulo r3(
				getCorner(1),
				getCorner(2),
				getCorner(6),
				getCorner(5));
		//r3.getTex()=tex;
		r3.render();
		Rectangulo r4(
				getCorner(1),
				getCorner(0),
				getCorner(4),
				getCorner(5));
		//r2.getTex()=tex;
		r4.render();
		Rectangulo r5(
				getCorner(3),
				getCorner(7),
				getCorner(6),
				getCorner(2));
		//r3.getTex()=tex;
		r5.setCol(getCol());
		r5.render();
		glPopMatrix();
	}
};

#endif /* SOLID_RIGID_BODY_H_ */
